export const defaultBanners = [
  {
    id: 'b1',
    title: 'Discover the Magic of Play',
    subtitle: 'Safe, Creative & Educational Toys for Kids of All Ages',
    badgeText: 'FESTIVE SALE • UP TO 40% OFF',
    ctaText: 'Shop All Toys',
    linkUrl: '/shop',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=1200&q=80',
    bgGradient: 'from-amber-400 via-orange-300 to-toy-orange',
    isActive: true,
    order: 0,
  },
  {
    id: 'b2',
    title: 'High-Speed RC Turbo Cars',
    subtitle: 'Rechargeable, 360° stunt drifting with LED headlights',
    badgeText: 'BOYS & GIRLS BESTSELLER',
    ctaText: 'Explore RC Cars',
    linkUrl: '/category/rc-vehicles',
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=1200&q=80',
    bgGradient: 'from-blue-400 via-indigo-300 to-toy-blue',
    isActive: true,
    order: 1,
  },
];

export const defaultCategories = [
  {
    id: 'c1',
    name: 'Educational & STEM',
    slug: 'educational-stem',
    description: 'Science kits, building blocks, and brain-teasing puzzles',
    icon: 'Brain',
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=600&q=80',
    color: '#2EC4B6',
  },
  {
    id: 'c2',
    name: 'RC Vehicles & Cars',
    slug: 'rc-vehicles',
    description: 'High-speed remote control stunt cars and helicopters',
    icon: 'Car',
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=600&q=80',
    color: '#FF7844',
  },
  {
    id: 'c3',
    name: 'Soft Plush & Dolls',
    slug: 'soft-plush',
    description: 'Ultra-cuddly teddy bears and premium soft toys',
    icon: 'Heart',
    image: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=600&q=80',
    color: '#F72585',
  },
  {
    id: 'c4',
    name: 'Puzzles & Board Games',
    slug: 'puzzles-games',
    description: 'Family board games and creative strategy puzzles',
    icon: 'Gamepad2',
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=600&q=80',
    color: '#7209B7',
  },
];

export const defaultProducts = [
  {
    id: 'p1',
    title: 'Dancing Robot with Smart LED Lights & Music',
    slug: 'dancing-robot-with-lights-music',
    description: 'Exciting 360-degree rotating stunt dancing robot with colorful LED lights, lively beats, and auto obstacle avoidance.',
    price: 799,
    compareAtPrice: 1299,
    discount: 38,
    images: '["https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80"]',
    categoryId: 'c1',
    category: defaultCategories[0],
    ageGroup: '3-5 Years',
    stock: 25,
    isFeatured: true,
    isTrending: true,
    isBestseller: true,
    rating: 4.9,
    reviewsCount: 48,
    safetyInfo: '100% Non-Toxic, BPA Free, Safe for Kids',
    brand: 'PlayMiso',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    title: '4WD High-Speed Monster Stunt RC Car',
    slug: '4wd-high-speed-monster-stunt-rc-car',
    description: 'Rechargeable 2.4GHz remote control all-terrain rock crawler with shock absorbers and double-sided flipping action.',
    price: 1299,
    compareAtPrice: 1999,
    discount: 35,
    images: '["https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80"]',
    categoryId: 'c2',
    category: defaultCategories[1],
    ageGroup: '6-8 Years',
    stock: 18,
    isFeatured: true,
    isTrending: true,
    isBestseller: true,
    rating: 4.8,
    reviewsCount: 36,
    safetyInfo: 'Child-Safe Rounded Plastic & Battery Enclosure',
    brand: 'PlayMiso',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    title: 'Giant Soft Plush Teddy Bear (60cm)',
    slug: 'giant-soft-plush-teddy-bear-60cm',
    description: 'Ultra-soft hugging teddy bear made with hypoallergenic microfiber plush fabric. Perfect birthday gift for toddlers and kids.',
    price: 899,
    compareAtPrice: 1499,
    discount: 40,
    images: '["https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80"]',
    categoryId: 'c3',
    category: defaultCategories[2],
    ageGroup: '0-2 Years',
    stock: 30,
    isFeatured: true,
    isTrending: false,
    isBestseller: true,
    rating: 5.0,
    reviewsCount: 52,
    safetyInfo: 'Hypoallergenic, Washable, Safe for Toddlers',
    brand: 'PlayMiso',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    title: 'STEM Solar Power Explorer Robot 12-in-1 Kit',
    slug: 'stem-solar-power-explorer-robot-12-in-1-kit',
    description: 'Build 12 different solar-powered walking, rolling, and floating robots. Teaches renewable green energy and mechanical engineering.',
    price: 1149,
    compareAtPrice: 1899,
    discount: 39,
    images: '["https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80"]',
    categoryId: 'c1',
    category: defaultCategories[0],
    ageGroup: '9+ Years',
    stock: 14,
    isFeatured: true,
    isTrending: true,
    isBestseller: false,
    rating: 4.7,
    reviewsCount: 29,
    safetyInfo: '100% Non-Toxic Plastic, Safe DIY Engineering Parts',
    brand: 'PlayMiso',
    createdAt: new Date().toISOString(),
  },
];
